In [250]:
import numpy as np
import kagglehub
import os
from PIL import Image
from IPython.display import display

# Download MNIST CSV dataset
path = kagglehub.dataset_download("oddrationale/mnist-in-csv")
print("Path to dataset files:", path)


Path to dataset files: C:\Users\ma\.cache\kagglehub\datasets\oddrationale\mnist-in-csv\versions\2


In [251]:

# Identify CSV files
csv_files = [f for f in os.listdir(path) if f.endswith('.csv')]
if not csv_files:
    raise FileNotFoundError(f"No CSV files found in {path}")

csv_path = os.path.join(path, csv_files[0])

# Load data
data = np.genfromtxt(csv_path, delimiter=',', skip_header=1)
labels = data[:, 0].astype(int)
pixels = data[:, 1:].astype(np.uint8)
scaled_pixels = pixels / 255.0


class Layer:
    def __init__(self, number, size, inputs=1):
        self.number = number
        self.size = size
        self.data = np.zeros((inputs, size), dtype=np.float32)

class Weight:
    def __init__(self, prev, next):
        self.value = (np.random.randn(prev.size, next.size).astype(np.float32))

class Bias:
    def __init__(self, next):
        self.value = np.random.randn(1, next.size).astype(np.float32)

class Neural:
    def __init__(self, activation):
        self.activation = activation
        self.layers = []
        self.weights = []
        self.biases = []

    def add_layer(self, layer):
        self.layers.append(layer)
        if len(self.layers) > 1:
            self.weights.append(Weight(self.layers[len(self.layers)-2], self.layers[len(self.layers)-1]))
            self.biases.append(Bias(self.layers[len(self.layers)-1]))

    def forward(self):
        for i in range(1, len(self.layers)):
            prev_data = self.layers[i - 1].data     
            w = self.weights[i - 1].value            
            b = self.biases[i - 1].value            
            z = np.dot(prev_data, w) + b            
            self.layers[i].data = self.activation(z)

    @property
    def output(self):
        return self.layers[len(self.layers)-1].data

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# cost function = (predicted-actual)^2 
def costFunction(predicted, actual):
    return np.sum((predicted - actual) ** 2)



In [252]:
input_taken = 5
indices = list(range(input_taken))

input_data = scaled_pixels[indices] 

actual = np.zeros((input_taken, 10), dtype=np.float32)
for i in range(len(indices)):
    idx = indices[i]
    label = labels[idx]
    actual[i, label] = 1
    display(Image.fromarray(pixels[idx].reshape(28,28), mode = 'L'))


print(actual)


[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [253]:

model = Neural(sigmoid)

input_layer = Layer(1, 784, inputs=input_taken)
input_layer.data = input_data

model.add_layer(input_layer)
model.add_layer(Layer(2, 107, inputs=input_taken))
model.add_layer(Layer(3, 26, inputs=input_taken))
model.add_layer(Layer(4, 10, inputs=input_taken))

model.forward()

result = np.argmax(model.output, axis=1)
true_labels = labels[indices]

print("Predicted Labels:", result)
print("True Labels     :", true_labels)
print(model.output)

cost = costFunction(model.output,actual)
print("Cost:", cost)


Predicted Labels: [5 5 6 5 5]
True Labels     : [7 2 1 0 4]
[[0.13165463 0.87791834 0.23534604 0.79529965 0.45443978 0.95472108
  0.93066688 0.36202548 0.01535598 0.65906683]
 [0.25326957 0.94694569 0.26559103 0.85738459 0.92788408 0.97336568
  0.90641191 0.74803514 0.0216239  0.23379536]
 [0.16645115 0.81948302 0.28592992 0.92445558 0.93616324 0.97998047
  0.99400808 0.55479239 0.05628186 0.34538388]
 [0.36193754 0.5191423  0.51570104 0.63206737 0.87832432 0.98006918
  0.95387118 0.48102778 0.01162836 0.59911716]
 [0.03059016 0.3038731  0.78000861 0.89714172 0.9045798  0.98221256
  0.96735536 0.20426702 0.12714564 0.76702225]]
Cost: 22.67025639268486


In [254]:
def sigmoid_prime(x):
    s = sigmoid(x)
    return s * (1 - s)

In [255]:
# print(model.biases[-1].value)

# print(model.weights[-1].value)

In [256]:
print(true_labels)
print(result)
# print(scaled_pixels)
# print(model.output)


[7 2 1 0 4]
[5 5 6 5 5]


In [290]:
arra = np.array(true_labels)

In [305]:
# print(result)
# print(true_labels)
# print(len(model.layers[-1]))
# print(model.layers[-1].data)

# print(arra.size)        #arra is np array
# print(result.size)      #result is np array
# print(result.shape)
# print(arra.shape)
# print(arra - result)
# print(model.layers[-1].data.size)
# print(model.layers[-1].data.shape)
# print(sigmoid_prime(model.layers[-1].data))



# sigmoid_deactivatedMAtrix = sigmoid_prime(model.layers[-1].data)
# differenc = np.array([arra - result])
# print(differenc.shape)
# differenc.reshape(-1, 1)
# print(differenc.shape)
# extended = np.repeat(differenc, 5, axis = 1)
# print(difference)


In [304]:
# a = np.array(differenc)   
# a = a.reshape(-1, 1)           

# repeat = np.repeat(a, 10, axis=1) 
# print(repeat.shape)  
# print(repeat)

# print(repeat * sigmoid_deactivatedMAtrix)




In [303]:
# a = np.array(arra)   
# a = a.reshape(-1, 1)           

# repeated = np.repeat(a, 10, axis=1) 
# print(repeated.shape)  
# print(repeated)

In [ ]:
def delta_lastlayer(actual, predicted, deactivated_matrix):
    number = input_taken
    difference = actual - predicted
    a = np.array(difference)   
    a = a.reshape(-1, 1)           
    repeated = np.repeat(a, 10, axis=1) 

    ans = (repeated) * sigmoid_prime(deactivated_matrix)
    return ans



In [300]:
arrrr = delta_lastlayer(arra, result, model.layers[-1].data )
# print(arrrr)
# print(arrrr.size)
# print(arrrr.shape)

In [301]:
def delta_calc(current_layer_number ):   #give current layer in backward terms like -1-2-3 and so on
    if (current_layer_number == -1):
        return arrrr
    else:
        answer = np.dot(delta_calc(current_layer_number + 1), np.transpose(model.weights[current_layer_number + 1].value)) * sigmoid_prime(model.layers[current_layer_number].data)
        # print(answer)
        return answer

In [ ]:
# model.layers[-4].size

784

In [340]:
numberOfWeightOrBiasMatrices = 3
delta_list = []     #deltas will be stored in order -3 , -2, -1 that is (for layer 1, layer 2, layer 3(output layer))
for i in (range(numberOfWeightOrBiasMatrices)):
    temp = delta_calc(i - numberOfWeightOrBiasMatrices)
    delta_list.append(temp)
    print("Shape of delta matrix of Layer",i-numberOfWeightOrBiasMatrices,temp.shape)

print(len(delta_list))      #no. of delta matrices added
print(delta_list[2])

Shape of delta matrix of Layer -3 (5, 107)
Shape of delta matrix of Layer -2 (5, 26)
Shape of delta matrix of Layer -1 (5, 10)
3
[[ 0.49783963  0.41480579  0.49313994  0.42858209  0.47504876  0.40137549
   0.40563914  0.48396852  0.49997053  0.44940573]
 [-0.73810015 -0.60413857 -0.73692796 -0.62744988 -0.60919377 -0.59705684
  -0.61483024 -0.65414487 -0.74991233 -0.73984385]
 [-1.2413817  -1.06157434 -1.22479541 -1.01682995 -1.01167316 -0.99211809
  -0.98577854 -1.15854159 -1.24901063 -1.21345068]
 [-1.20994036 -1.16942206 -1.17044101 -1.13301912 -1.03684066 -0.99207811
  -1.0038174  -1.18039116 -1.24995775 -1.14421523]
 [-0.24994152 -0.24431649 -0.21552221 -0.20574793 -0.20510274 -0.19822236
  -0.19955841 -0.24741022 -0.24899234 -0.21655622]]


In [343]:
check = [[1,2,3,4,5], [1,2,3,4,5]]
sum = np.sum(check, axis = 0)

print(sum)

[ 2  4  6  8 10]


In [357]:
def dJdW(current_layernumber):         #input layer number in negatives
    input_of_current_layer = np.transpose(model.layers[current_layernumber-1].data)
    ans = np.dot(input_of_current_layer, delta_calc(current_layernumber) )
    return ans


In [359]:
print(dJdW(-1).shape)
dJdW(-1)

(26, 10)


array([[-1.35807005e+00, -1.17067634e+00, -1.32737372e+00,
        -1.10785493e+00, -1.04349005e+00, -1.08593307e+00,
        -1.08801470e+00, -1.23250427e+00, -1.37099564e+00,
        -1.36228320e+00],
       [ 1.05742676e-03,  8.85592940e-04,  1.04473931e-03,
         9.15000083e-04,  1.05924678e-03,  8.51684711e-04,
         8.55397230e-04,  1.06006723e-03,  1.05757729e-03,
         9.16529757e-04],
       [-9.39156044e-02, -8.06316604e-02, -9.25656240e-02,
        -7.64362965e-02, -7.48596930e-02, -7.49729591e-02,
        -7.43350759e-02, -8.72006098e-02, -9.45146385e-02,
        -9.26638161e-02],
       [-1.86912646e+00, -1.76275596e+00, -1.79078182e+00,
        -1.64654506e+00, -1.50371436e+00, -1.51304851e+00,
        -1.51823131e+00, -1.78335932e+00, -1.91037184e+00,
        -1.80287988e+00],
       [-2.93511155e+00, -2.65915512e+00, -2.84817791e+00,
        -2.54888761e+00, -2.38298102e+00, -2.37287907e+00,
        -2.39293101e+00, -2.75103392e+00, -2.99130112e+00,
        -2.

In [351]:
def dJdB(currentlayernumber):       #input layer number in negatives
    ans = np.sum(delta_calc(currentlayernumber), axis = 0)
    return ans

In [356]:
print(dJdB(-2))
print(dJdB(-1))
#we can use a loop here

[ 0.59652672  0.66214102  0.36173751  1.62630006  1.06536968  1.63841734
 -1.2415656   1.01320154 -0.91006385 -0.2513158  -2.02395219 -2.55362031
  1.12229002 -0.27563072 -3.12038304 -0.27396123 -4.09944757 -2.06745125
 -1.80373803  1.93663732 -0.34316364 -0.81298095 -2.63691956  0.11253313
  1.91787666  1.1654949 ]
[-2.94152411 -2.66464567 -2.85454665 -2.55446479 -2.38776157 -2.37809992
 -2.39834544 -2.75651931 -2.99790253 -2.86466026]
